development:
  adapter: mysql
  encoding: utf8
  database: yars_dev
  pool: 5
  username: root
  password:
#  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql
  encoding: utf8
  database: yars_test
  pool: 5
  username: root
  password:
#  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql
  encoding: utf8
  database: yars_prod
  pool: 5
  username: root
  password: 
#  socket: /var/run/mysqld/mysqld.sock